INSERT INTO public.APP_PRODUCT (PRODUCT_TITLE, PRODUCT_PRICE) VALUES ('Телевизор',1000000);
INSERT INTO public.APP_PRODUCT (PRODUCT_TITLE, PRODUCT_PRICE) VALUES ('Смартфон',500000);
INSERT INTO public.APP_PRODUCT (PRODUCT_TITLE, PRODUCT_PRICE) VALUES ('Соковыжималка',150000);
INSERT INTO public.APP_PRODUCT (PRODUCT_TITLE, PRODUCT_PRICE) VALUES ('Наушники',50000);
INSERT INTO public.APP_PRODUCT (PRODUCT_TITLE, PRODUCT_PRICE) VALUES ('Клавиатура',75000);

INSERT INTO public.APP_USER (USER_NAME, USER_LAST_NAME, USER_AGE) VALUES ('Иван','Иванов', 10);

INSERT INTO public.APP_CREDENTIALS (USER_ID, USER_LOGIN, USER_PASS) VALUES (1,'user', '739k�-q���9n�');
