DROP TABLE IF EXISTS public.APP_USER;
DROP TABLE IF EXISTS public.APP_CREDENTIALS;
DROP TABLE IF EXISTS public.APP_PURCHASE;

CREATE TABLE public.APP_USER (
    USER_ID SERIAL,
    USER_NAME VARCHAR(20) UNIQUE NOT NULL,
    USER_LAST_NAME VARCHAR(20) UNIQUE NOT NULL,
    USER_AGE INTEGER,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE public.APP_CREDENTIALS (
    CREDENTIALS_ID SERIAL,
    USER_ID DECIMAL,
    USERNAME VARCHAR,
    USER_PASS VARCHAR,
    ACTIVE BOOLEAN,
    ROLES VARCHAR,
    PRIMARY KEY (CREDENTIALS_ID)
);

CREATE TABLE public.APP_PURCHASE (
    PURCHASE_ID SERIAL,
    PURCHASE_NAME VARCHAR,
    COUNT_OF_PURCHASE INTEGER,
    PURCHASE_AMOUNT DECIMAL,
    BUYERS_ID INTEGER,
    PURCHASE_DATE DATE,
    PRIMARY KEY (PURCHASE_ID)
);



