DROP TABLE public.APP_USER;
DROP TABLE public.APP_CREDENTIALS;
DROP TABLE public.APP_PRODUCT;
DROP TABLE public.APP_PURCHASE;

CREATE TABLE public.APP_USER (
    USER_ID SERIAL,
    USER_NAME VARCHAR(20) UNIQUE NOT NULL,
    USER_LAST_NAME VARCHAR(20) UNIQUE NOT NULL,
    USER_AGE INTEGER,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE public.APP_CREDENTIALS (
    CREDENTIALS_ID SERIAL,
    USER_ID DECIMAL,
    USER_LOGIN VARCHAR,
    USER_PASS VARCHAR,
    PRIMARY KEY (CREDENTIALS_ID)
);

CREATE TABLE public.APP_PRODUCT (
    PRODUCT_ID SERIAL,
    PRODUCT_TITLE VARCHAR(100) UNIQUE NOT NULL,
    PRODUCT_PRICE DECIMAL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE public.APP_PURCHASE (
    PURCHASE_ID SERIAL,
    PURCHASE_ITEM DECIMAL,
    COUNT_OF_PRODUCTS INTEGER,
    PURCHASE_AMOUNT DECIMAL,
    BUYERS_ID INTEGER,
    PURCHASE_DATE DATE,
    PRIMARY KEY (PURCHASE_ID)
);



