CREATE TABLE IF NOT EXISTS APP_USER (
    USER_ID SERIAL,
    USER_NAME VARCHAR(20) UNIQUE NOT NULL,
    USER_LAST_NAME VARCHAR(20) UNIQUE NOT NULL,
    USER_AGE INTEGER,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS APP_CREDENTIALS (
    CREDENTIALS_ID SERIAL,
    USER_ID DECIMAL,
    USER_LOGIN VARCHAR,
    USER_PASS VARCHAR,
    PRIMARY KEY (CREDENTIALS_ID)
);

CREATE TABLE IF NOT EXISTS APP_PRODUCT (
    PRODUCT_ID SERIAL,
    PRODUCT_TITLE VARCHAR(100) UNIQUE NOT NULL,
    PRODUCT_PRICE DECIMAL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS APP_PURCHASE (
    PURCHASE_ID SERIAL,
    PURCHASE_ITEM DECIMAL,
    COUNT_OF_PRODUCTS INTEGER,
    PURCHASE_AMOUNT DECIMAL,
    BUYERS_NAME VARCHAR(300),
    BUYERS_LAST_NAME VARCHAR(300),
    BUYERS_AGE INTEGER,
    PURCHASE_DATE DATE,
    PRIMARY KEY (PURCHASE_ID)
);



